apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
    - componentName: example-component
      parameterValues:
        - name: instance-name
          value: example-appconfig-workload
        - name: image
          value: nginx:1.17
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: example-appconfig-trait
            spec:
              replicaCount: 3
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ServiceExpose
            metadata:
              name:  example-appconfig-trait
            spec:
              # Under template you can define all fields of K8S native service which you want
              template:
                type: NodePort
                ports:
                  - port: 80
                    name: nginx
                    targetPort: 80