name: Docker

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        repository: oam-dev/catalog

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
      
    - name: Build
      run: make build

    - name: Build Bin
      run: |
        mkdir bin
        for x in traits/*/
        do
          name=${x%?}
          name=${name##*/}
          binFile="${x}bin/manager"
          [[ -f $binFile ]] || break
          cp -a $binFile ./bin/$name
        done
        ls bin
        echo 'FROM ubuntu:focal' >> Dockerfile
        echo 'WORKDIR /root/app' >> Dockerfile
        echo 'COPY ./* ./' >> Dockerfile
        cat Dockerfile

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Docker repository to tag the image with
        repository: oamboot/catalog
        # Automatically tags the built image with the git short SHA as per the readme
        tags: ${{ github.event.inputs.version }}
        # Path to the build context
        path: bin
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: Dockerfile
